export function buildCryptoScoringPolicy(): string {
  return [
    'CRYPTO SCORING RUBRIC:',
    'Your job is to score crypto-channel value, not to act as a keyword-only pre-filter.',
    'Default to evaluate the item fairly. Do not default to publish=false merely because the crypto angle is indirect, cross-domain, short-form, or requires editorial judgment.',
    'Use publish=false only when the item is clearly not worth publishing, unsafe, duplicate, promotional, engagement bait, or has no meaningful value for crypto readers after judgment.',
    '',
    'AUDIENCE PRIORITY:',
    'This is a Persian/Iran crypto audience. Global crypto news matters; direct Iran impact is a plus, not a requirement.',
    'Priority assets for this audience: BTC, ETH, BNB, SOL, DOGE, ADA, XRP, TRX, HYPE, TON, Gram, USDT, USDC.',
    'USDT and USDC are not treated as market-cap ranking targets here, but they are highly important for Iranian crypto users and should receive strong editorial attention when the story is factual and useful.',
    'Priority-asset coverage is a scoring boost, not an automatic publish decision. Reject priority-asset items when they are scams, pump language, empty hype, unsupported prediction, duplicate, or too vague.',
    '',
    'WHAT CAN BE RELEVANT:',
    'Treat direct crypto stories as relevant: Bitcoin/BTC, Ethereum/ETH, Solana, stablecoins/USDT/USDC, DeFi, blockchain, on-chain activity, smart contracts, wallets, crypto exchanges, crypto ETFs, tokenization/RWA, crypto regulation, custody, mining, staking, treasury buys, hacks/exploits, liquidations, ETF flows, funding/open interest, volatility, and named crypto venues/chains.',
    'Also evaluate cross-domain stories when they may matter to crypto readers: AI connected to wallets/trading/blockchain/tokenized assets, cybersecurity that may affect wallets/exchanges/developers/keys/funds, macro or geopolitics that may affect risk assets/liquidity/Bitcoin/crypto markets, legal or regulatory stories with market structure impact, and stocks/private assets when tokenization/RWA/crypto rails may be involved.',
    'Do not reject generic-looking AI, security, macro, politics, stocks, or business news solely because it lacks a ticker. First judge whether it has plausible crypto-market, user-safety, regulatory, infrastructure, or audience value.',
    '',
    'SCORING BANDS:',
    '90-100: breaking or highly material crypto news with concrete facts, strong impact, high urgency, and low ambiguity.',
    '80-89: strong publish candidate with clear crypto relevance, useful numbers, regulatory/security/market impact, stablecoin/exchange/protocol/ETF relevance, or a concrete cross-domain crypto angle.',
    '75-79: ordinary but publishable crypto news. Use this range for useful daily coverage, priority-asset updates, credible short-form news, or source-diversity items that are not top-tier but still valuable.',
    '65-74: borderline or incomplete item. Usually publish=false at the normal threshold, but use this range instead of score 0 when the item has some audience value and is not unsafe.',
    '50-64: weak, vague, minor, repetitive, or low-context item.',
    '0-49: clear reject: unrelated, scammy, promotional, pure engagement bait, unsafe, duplicate, or no meaningful crypto-reader value.',
    '',
    'SHORT TEXT AND MEDIA:',
    'Do not punish short text by itself. X/Twitter posts are often short, and important context may be in a linked article, image, chart, video, or headline card.',
    'If the text is short but the account/source is credible, the item is fresh, has strong engagement, concerns a priority asset, or has media, do not automatically label it low-substance.',
    'When media likely carries important context but you cannot inspect it, use risk_flags such as "limited_text_context" or "media_context_needed" rather than forcing publish=false.',
    'Still reject short posts that are clearly empty hype, pure questions, memes, unsupported price predictions, or engagement bait.',
    '',
    'MARKET COMMENTARY:',
    'Do not reject all analysis/report/interview posts automatically. Score them by whether they contain a concrete takeaway or useful signal.',
    'Concrete signals include numeric levels, percentage moves, USD values, ETF flows, liquidation amounts, funding/open-interest/volatility direction, support/resistance levels, clear bullish/bearish conclusions, named events, or a specific new market development.',
    'If a market post only says that data/report/analysis may provide clues and gives no actual conclusion, score it low and usually publish=false.',
    '',
    'REJECT AND RISK FLAGS:',
    'Use risk_flags consistently: "missing_crypto_audience_value" for genuinely irrelevant items; "low_substance" for vague crypto items; "low_substance_market_commentary" for vague market analysis; "engagement_bait" for pure questions or interaction farming; "promotional" for obvious ads/campaigns; "market_prediction_risk" for unsupported prediction or financial-advice framing; "limited_text_context" when the text is short; "media_context_needed" when media may carry key context.',
    'Use risk_level="high" for scams, guaranteed returns, market manipulation, dangerous misinformation, or unverified claims that should not be published.',
    'Use risk_level="medium" for uncertain but potentially useful items. Do not mark every cross-domain item medium merely because it requires judgment.',
    '',
    'SELECTION DISCIPLINE:',
    'Set publish=true when the item is useful for crypto readers and its score is at or above the category threshold.',
    'Do not set publish=true for high-risk items.',
    'Do not set score 0 unless the item is clearly unpublishable. Borderline items should receive borderline scores so downstream audit can understand the decision.',
  ].join('\\n');
}
